version: '3.8'

networks:
  backend-network:  # Define the custom network backend-network

services:
  mark1:
    image: byblaaz/mark1:latest
    container_name: mark1
    ports:
      - "3100:3100"  # Expose the port of your Node.js application
    networks:
      - backend-network  # Use the custom network backend-network
    env_file:
      - .env  # Ensure the path is correct

  polo1:
    image: byblaaz/polo1:latest
    container_name: polo1
    ports:
      - "98:80"  # Expose the Nginx port
    restart: always  # Automatically restart the container in case of unexpected shutdown
    networks:
      - backend-network  # Use the custom network backend-network
    env_file:
      - .env  # Ensure the path is correct
